import React, { useState } from 'react'
import FormField from '../Components/FormField'
import Loader from '../Components/Loader'
import Card from '../Components/Card'

const RenderCards = ({ data, title }) => {
    if (data?.length > 0) return (
        data.map((post) => <Card key={post._id} {...post} />)
    )
    return (
        <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState([]);
    const [search, setSearch] = useState("");

    return (
        <section className='max-w-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
                <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Browse here, a collection of visually stunning images generated by DALL-E</p>
            </div>
            <div className='mt-16'>
                <FormField
                    labelName="Search posts"
                    type="text"
                    name="text"
                    placeholder="Search something..."
                // value={searchText}
                // handleChange={handleSearchChange}
                />
            </div>

            <div className='mt-10'>
                {loading ? (
                    <div className='flex justify-center items-center'>
                        <Loader />
                    </div>
                ) : (
                    <>
                        {search && (
                            <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                                Showing results for <span className='font-bold text-[#222328]'>{search}</span>
                            </h2>
                        )}
                        <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                            {search ? (
                                <RenderCards data={[]} title="No search results found" />
                            ) : (
                                <RenderCards data={[]} title="No posts found" />
                            )}
                        </div>
                    </>
                )}
            </div>
        </section>
    )
}

export default Home
